== PP-Module for Client Virtualization

[cols="1,1,1,1,1,1,1,1"]
|===
8+|clientvirtualization 
| https://github.com/commoncriteria/clientvirtualization/tree/master[master] 
a| https://commoncriteria.github.io/clientvirtualization/master/clientvirtualization-release.html[📄]
a|[link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/master/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/master/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/master/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/master/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/master/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/master/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/master/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/master/transforms.svg[transforms,150]
a| [link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/master/HTMLs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/master/html_count.svg[HTML Count]
[link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/master/PDFs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/master/pdf_count.svg[PDF Count]

| https://github.com/commoncriteria/clientvirtualization/tree/release-1.1[release-1.1] 
a| https://commoncriteria.github.io/clientvirtualization/release-1.1/clientvirtualization-release.html[📄]
a|[link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/release-1.1/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/release-1.1/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/release-1.1/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/release-1.1/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/release-1.1/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/release-1.1/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/release-1.1/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/release-1.1/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/release-1.1/transforms.svg[transforms,150]
a| [link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/release-1.1/HTMLs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/release-1.1/html_count.svg[HTML Count]
[link=https://github.com/commoncriteria/clientvirtualization/blob/gh-pages/release-1.1/PDFs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/clientvirtualization/gh-pages/release-1.1/pdf_count.svg[PDF Count]

|===

https://github.com/commoncriteria/clientvirtualization/issues[image:https://img.shields.io/github/issues/commoncriteria/clientvirtualization.svg?maxAge=2592000[GitHub
issues Open]]

This repository hosts the draft version of the PP-Module for Client
Virtualization based on the
https://commoncriteria.github.io/pp/clientvirtualization/clientvirtualization-esr.html[Essential
Security Requirements (ESR)] for this technology class of products. This
repository is used to facilitate collaboration and development on the
draft document. See the link:#Release-Version[release] section if you
are looking for the officially released version for evaluations. A list
of products that have passed evaluation against this PP-Module can be
found https://www.niap-ccevs.org/Profile/Info.cfm?id=409[here].

=== Draft Version

* https://commoncriteria.github.io/pp/clientvirtualization/clientvirtualization-release.html[PP-Module
for Client Virtualization] (html)
* https://commoncriteria.github.io/pp/clientvirtualization/clientvirtualization-release.pdf[PP-Module
for Client Virtualization] (pdf)
* https://commoncriteria.github.io/pp/clientvirtualization/clientvirtualization-sd.html[Supporting
Documents for Client Virtualization] (html)
* https://commoncriteria.github.io/pp/clientvirtualization/clientvirtualization-sd.pdf[Supporting
Documents for Client Virtualization] (pdf)

=== Release Version

* https://www.niap-ccevs.org/Profile/Info.cfm?id=409[Extended Package
for Client Virtualization]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/clientvirtualization/issues[repository
issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/clientvirtualization.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]

pandoc version 3.1.2
